branches:
  - name: master
    protection:
      required_status_checks:
        strict: true
        contexts:
          - lint
          - test
          - build
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions: null 