branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - test
          - build
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions: null 